### ISSUE TITLE
[FEAT]: add replay button

### ISSUE THREAD

**Issue by Ananya2001-an** [Ananya2001-an/githubwars#16]
### Discussed in https://github.com/Ananya2001-an/githubwars/discussions/15

<div type='discussions-op-text'>

<sup>Originally posted by **wanickols01** February 10, 2023</sup>
# Replay button
## Issue
Currently when we play there nothing to restart the game besides pressing the back button. 
## Solution
A simple and useful feature to solve this would be a "Battle Again" button so that they app can reset. </div>

**Comment by Halim-Shams** [comment]
I can work on this task.
