### ISSUE TITLE
[FEATURE]: add profile link

### ISSUE THREAD

**Issue by Ananya2001-an** [Ananya2001-an/githubwars#18]
**Is your feature request related to a problem? Please describe.**
Add link to user's github profile when showing results at the end.

**Describe the solution you'd like**
 The link should be like an icon over the user's avatar.

**Comment by abhijeet-26** [comment]
@Ananya2001-an  Can I work on it?

**Comment by Ananya2001-an** [comment]
Sure I will assign you

**Comment by abhijeet-26** [comment]
I will work on weekends because in weekdays I have a 9 to 5 job. Is it okay?

**Comment by Ananya2001-an** [comment]
> I will work on weekends because in weekdays I have a 9 to 5 job. Is it okay?

Of course @abhijeet-26 you don't have to stress about it. Your contribution matters so please take it easy.

**Comment by abhijeet-26** [comment]
@Ananya2001-an  Sukriya 🙏
