### ISSUE TITLE
Save the user1 in Local storage

### ISSUE THREAD

**Issue by JasonDsouza212** [Ananya2001-an/githubwars#26]
**Is your feature request related to a problem? Please describe.**
- We almost always try to access our GitHub profile, and it would be a good idea to store it in the local storage once a username1  enters their data.
- This way, they won't have to re-enter their username again when they use it next time.

**Describe the solution you'd like**
- When someone uses this website for the first time, the local storage will be empty. 
- However, once they enter their username1, it should automatically be stored in the local storage.
- Then, the next time they click on 'battle Again', the username1 should pop up automatically and give them the ability to edit it

**Comment by Ananya2001-an** [comment]
That's a good idea @JasonDsouza212 but then what if the user1 wants to try out someone else's username ?

**Comment by JasonDsouza212** [comment]
You'll give him the option to edit it too . You will be just filling out the value for him but he can change it if he wants

**Comment by Ananya2001-an** [comment]
> You'll give him the option to edit it too . You will be just filling out the value for him but he can change it if he wants

Sounds good. Do you want to work on this?

**Comment by JasonDsouza212** [comment]
Ya I think I can work on that
