### ISSUE TITLE
[BUG]: Change GitHub logo on dark mode

### ISSUE THREAD

**Issue by refilwe-m** [Ananya2001-an/githubwars#28]
Not really a bug but a **UI issue**:
When you switch to dark mode, the GitHub logo isn't changed to a whiter one, the contrast doesn't look good there. It would be more ideal that if you switch to dark mode, the logo changes too to maybe this one: 
![image](https://user-images.githubusercontent.com/39610552/220294929-b3e3272c-1b01-43a9-8ab6-47dcfccb57e6.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/39610552/220294290-b3ae294a-33b1-40b3-a36d-4971c8251fec.png)
Light mode
![image](https://user-images.githubusercontent.com/39610552/220294378-b0ca8b6b-cfc2-418a-9119-33dd1b36b832.png)
Dark Mode

**Comment by Ananya2001-an** [comment]
Nice catch @refilwe-m! You can work on this.

**Comment by abhijeet-26** [comment]
Is anyone working on it now?

**Comment by refilwe-m** [comment]
> Is anyone working on it now?
I am on it, was just occupied, expect a PR today😊
