### ISSUE TITLE
[FEATURE] Getting random GitHub username 

### ISSUE THREAD

**Issue by Ananya2001-an** [Ananya2001-an/githubwars#4]
**Is your feature request related to a problem? Please describe.**
Instead of writing username manually for the second player it would be better to create a random GitHub username generator so that the game could be more fun.

**Describe the solution you'd like**
After the first user is selected we could automatically run the generator to fetch a random user.

**Additional context**
Use the github api to fetch all usernames/users. (need to look into the pagination concept for the response to this request)

**Comment by Jackerlus** [comment]
Hi there! Related to this issue, I'd like to submit a contribution in the form of a dedicated random button building off the contribution from @wanickols01 . I figure that would make it clearer to the user that a random option exists if they want to try the feature. Let me know if this sounds okay!

**Comment by Ananya2001-an** [comment]
@Jackerlus I am actually working on this issue right now but you can still go ahead and try to see if you are able to fetch random users using the api. Every contribution counts😊

**Comment by Jackerlus** [comment]
> @Jackerlus I am actually working on this issue right now but you can still go ahead and try to see if you are able to fetch random users using the api. Every contribution counts😊

Sure, I'll submit a pull request now and you can do with it whatever you feel is needed 😃
