### ISSUE TITLE
[BUG] GitHub icon link not working

### ISSUE THREAD

**Issue by Ananya2001-an** [Ananya2001-an/githubwars#5]
**Describe the bug**
On some pages the GitHub icon link is not responsive.

**Screenshots**
![image](https://user-images.githubusercontent.com/55504616/217724861-f2640fe5-02e7-4180-ae9e-48aa3ab33d33.png)

**Comment by strawHat121** [comment]
Hey,

Your project is very fun so I would like to contribute to this.

This bug seems like an easy place to start with so can I do this ?

**Comment by Ananya2001-an** [comment]
Sure go ahead!
